### ISSUE TITLE
Have students install bower

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/ember#10]
EDIT:

instructions to install bower globally later in readme after instructions to install dependencies with bower.  Consider moving before instructions to install dependencies.

Original:

bower is not install in installfest.  Students should run `npm install -g bower` before installing dependencies: npm install && bower install

**Comment by RealWeeks** [comment]
Refs: https://github.com/ga-wdi-boston/ember-study/issues/27

**Comment by jrhorn424** [comment]
<del>Wrong repo. This should be tracked over at `ember-template`.</del>

**Comment by gaand** [comment]
@jrhorn424 template or study?

**Comment by jrhorn424** [comment]
`ember-study`

**Comment by RealWeeks** [comment]
Will close this issue, since its tracked on ember-study. Please reopen if deemed necessary.

**Comment by RealWeeks** [comment]
Sorry, open unit resolved on ember-study to next person to prepare knows to check and remove/keep

**Comment by raq929** [comment]
Bower was successfully installed before this lesson for 015. Closing.
