### ISSUE TITLE
Run ember build and ember test

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/ember#12]
After changing all names in ember template.

Move step 6 above step 5.

Issue via @jrhorn424

**Comment by laurenfazah** [comment]
I think this is related to #8 ? If so, all set to close @jrhorn424

**Comment by payne-chris-r** [comment]
I don't know that that's what Jeff was asking for. @jrhorn424 care to comment?

**Comment by jrhorn424** [comment]
@ga-wdi-boston/core I believe this is tracked in the wrong repo. We may have changed repos over time, but I'm thinking this belongs over at `ember-template`.

**Comment by jrhorn424** [comment]
I'll go check it for changes.

**Comment by jrhorn424** [comment]
I believe the "step moving" has been accomplished over at `ember template`, but the original issue title is still unaddressed. Closing and moving over there.

**Comment by jrhorn424** [comment]
Now tracked at https://github.com/ga-wdi-boston/ember-template/issues/10

**Comment by payne-chris-r** [comment]
I had a feeling that was the case, but didn't know your original intent. Thanks for fixing it.
