### ISSUE TITLE
Add link to layer diagram from Ember docs to research lab

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/ember#13]
https://guides.emberjs.com/v2.5.0/getting-started/core-concepts/ (use whatever the latest is)

**Comment by laurenfazah** [comment]
Seems to be linked in 2.0 explanation. Is it meant to be elsewhere or can this be closed? @jrhorn424

**Comment by laurenfazah** [comment]
JK I now understand - image is in the research lab now

**Comment by raq929** [comment]
This image is currently in the repo. Closing.
