### ISSUE TITLE
Update README to satisfy `.remarkrc`

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/ember#2]
Update README to satisfy `.remarkrc`
Use 'developers' instead of 'students'

**Comment by jrhorn424** [comment]
What does this mean?

**Comment by MattB-GA-Boston** [comment]
Sorry, I'll clarify.

**Comment by jrhorn424** [comment]
Thanks.

**Comment by jrhorn424** [comment]
I belive this is addressed. @MattB-GA-Boston
