### ISSUE TITLE
Remove CA at end

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/ember#26]
This talk often takes 1-2 units, but runs as long as time allows with whatever we want to talk about--meaning it isn't pointed, probably trails off, and could be cut shorter. If there aren't comments to this effect on #4, there should be. It's kind of a fun time to play around, but the material should probably be covered in a D/CA/L format in `ember-routing` instead of here.

Lauren's comment says it all:
```
Lecture itself was only about 60 minutes for me. We spent the rest of the time up to lunch generating both static and dynamic routes and components to play around. Put most emphasis on browser paths mapping to router mapping to routes and associated templates.
```

**Comment by MicFin** [comment]
Can this be closed per https://github.com/ga-wdi-boston/ember/pull/27?
